steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - HelloHTTP
      - --source=.
      - --trigger-http
      - --allow-unauthenticated
