steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: /bin/bash
    args:
    - -c
    - | 
      gcloud secrets versions access latest  --secret=firestore-ads > firestore.json
      export GOOGLE_APPLICATION_CREDENTIALS=firestore.json
  - name: golang
    entrypoint: /bin/bash
    args:
    - -c
    - | 
      mkdir public
      mv template/iklan.png public
      go run cmd/static/main.go
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: /bin/bash
    args:
    - -c
    - |
      gcloud functions deploy Main --source=. --trigger-http --allow-unauthenticated
