steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
    - '-c'
    - | 
      gcloud secrets versions access latest  --secret=firestore-secret > firestore.json
      export GOOGLE_APPLICATION_CREDENTIALS=firestore.json
  - name: "golang"
    entrypoint: /bin/bash
    args:
    - '-c'
    - | 
      mkdir public
      go run cmd/static/main.go
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - Main
      - --source=.
      - --trigger-http
      - --allow-unauthenticated
