name: build

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls
      - run: mkdir serverless_function_source_code && mkdir static && mkdir template
      - run: printf '<html>{{.title}}{{.name}}</html>' > app.html
      - run: printf '{{define "index"}}<html>{{.title}}{{.name}}</html>{{end}}' > index.html
      - run: cp *html serverless_function_source_code && cp *html template
      - run: go build -v ./...
      - run: go test -race -covermode atomic -coverprofile=covprofile ./...
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github
